blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('comment/<int:id>/remove', views.delete_comment, name='remove_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # profile
    path('profile/', views.user_profile, name='user_profile'),
    # others
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('contact/thank-you/', TemplateView.as_view(template_name='others/contact_thank_you.html'),
         name='contact_thank_you'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.post_list),  # new
    path('blog/', include('blog.urls', namespace='blog')),
    path('', views.register, name='register'),
    # auth views
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True)

    def __str__(self):
        return f"{self.user.username}"


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    publish_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts"
    )

    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ["-publish_at"]
        indexes = [
            models.Index(fields=["-publish_at"]),
        ]

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish_at.year,
                self.publish_at.month,
                self.publish_at.day,
                self.slug
            ]
        )

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments"
    )

    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_at"]
        indexes = [
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        return f"Comment by {self.profile.user.username} on {self.post}"

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Comment, Profile


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-control"}))
    first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passswords don't match")
        return cd["password2"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["date_of_birth", "photo"]


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='Your Name', widget=forms.TextInput())
    email = forms.EmailField(label='Your Email', widget=forms.EmailInput())
    message = forms.CharField(widget=forms.Textarea(), label='Your Message')

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from taggit.models import Tag

from blog.forms import UserRegistrationForm, CommentForm, ProfileEditForm, ContactForm
from blog.models import Post, Profile, Comment


def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        "post/list.html",
        {"posts": posts, "tag": tag},
    )


def post_detail(request, year, month, day, post):
    try:
        post = Post.published.get(
            slug=post,
            publish_at__year=year,
            publish_at__month=month,
            publish_at__day=day
        )
        comments = post.comments.filter(active=True)

        post_tags_ids = post.tags.values_list("id", flat=True)  # new
        similar_posts = Post.published.filter(
            tags__in=post_tags_ids
        ).exclude(id=post.id)
        similar_posts = similar_posts.annotate(
            same_tags=Count("tags")
        ).order_by("-same_tags", "-publish_at")[:4]

        form = CommentForm()
    except Post.DoesNotExist:
        raise Http404("No Post found.")
    return render(
        request,
        "post/detail.html",
        {
            "post": post,
            "form": form,
            "comments": comments,
            "similar_posts": similar_posts,
        }
    )


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, "account/register_done.html", {"user_form": user_form})
    else:
        user_form = UserRegistrationForm()

    return render(request, "account/register.html", {"form": user_form})


@login_required()
@require_POST
def post_comment(request, post_id):
    try:
        post = get_object_or_404(
            Post,
            id=post_id,
            status=Post.Status.PUBLISHED
        )
        comment = None
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()

        return render(
            request,
            "post/comment.html",
            {
                "post": post,
                "form": form,
                "comment": comment
            }
        )
    except Post.DoesNotExist:
        messages.error(
            request,
            "Invalid post."
        )
    except Exception:
        messages.error(
            request,
            "Cannot create comment. Please try again."
        )

    return redirect("blog:post_list")


@login_required
@require_POST
def delete_comment(request, id):
    try:
        comment = get_object_or_404(Comment, id=id, user=request.user)
        comment.delete()
        return HttpResponse("ok")
    except Exception:
        return HttpResponse("error", status=400)


@login_required
def user_profile(request):
    if request.method == "POST":
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES
        )
        if profile_form.is_valid():
            profile_form.save()

        return redirect("blog:post_list")
    else:
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, "account/settings.html", {"profile_form": profile_form})


def about(request):
    return render(request, "others/about.html")


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]

            send_mail(
                f"Contact Form Submission from {name}",
                message,
                email,
                ["kayahots@gmail.com"],
                fail_silently=False,
            )

            return redirect("blog:contact_thank_you")
    else:
        form = ContactForm()

    return render(request, "others/contact.html", {"form": form})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
</head>
<body>
<div class="container d-flex flex-column">
    <header class="d-flex flex-wrap justify-content-between align-items-center py-3 border-bottom">
        <a href="/" class="d-flex align-items-center mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img class="me-2" src="{% static 'images/logo.png' %}" alt="logo">
            <span class="fs-4">The Blog</span>
        </a>

        {% if request.user.is_authenticated %}
            <div class="dropdown">
                <div data-bs-toggle="dropdown" aria-expanded="false">
                    {% if request.user.profile.photo %}
                        <img class="profile-image" src="{{ request.user.profile.photo.url }}" alt="Profile image">
                    {% else %}
                        <div>{{ request.user.username }}</div>
                    {% endif %}
                </div>
                <ul class="dropdown-menu">
                    <li>
                        <form class="dropdown-item" action="{% url 'logout' %}" method="post">
                            <button class="btn">Logout</button>
                            {% csrf_token %}
                        </form>
                    </li>
                    <li>
                        <div class="dropdown-item">
                            <a class="btn" href="{% url 'blog:user_profile' %}">Settings</a>
                        </div>
                    </li>
                </ul>
            </div>
        {% else %}
            <a href="{% url 'login' %}" class="btn btn-secondary" data-cy="login-button">Login</a>
        {% endif %}
    </header>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible mt-2">
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}

    <main class="py-4">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="d-flex flex-wrap align-items-center justify-content-between py-3 border-top">
        <a href="/" class="footer-logo d-flex align-items-center link-body-emphasis text-decoration-none">
            <img class="me-2" src="{% static 'images/logo.png' %}" alt="logo" width="40">
            <span class="fs-4">The Blog</span>
        </a>

        <div class="d-flex">
            <a class="btn btn-link" href="{% url 'blog:about' %}">About</a>
            <a class="btn btn-link" href="{% url 'blog:contact' %}">Contact</a>
        </div>
        
        <div>Made by - Your name</div>
    </footer>

    <div class="toast-wrapper">
        <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body">

                </div>
                <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>